
set nocompatible
set backspace=indent,eol,start
set incsearch		" do incremental searching
set showcmd		" display incomplete commands
set ruler		" show the cursor position all the time
set noexpandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
syntax on
set number
set relativenumber
filetype plugin indent on



set list
set listchars=tab:›\ ,trail:˙
set modelines=5



" Need to set the undodir, backupdir and directory. Locations depend on the machine though.
set backup		" keep a backup file (restore to previous version)
set undofile		" keep an undo file (undo changes after closing)
"set undodir=/home/netcool/chirn36/.vim/.undo//
"set backupdir=/home/netcool/chirn36/.vim/.backup//
"set directory=/home/netcool/chirn36/.vim/.swp//



" Change tabs to 4 spaces in python
autocmd FileType python set expandtab
autocmd FileType python set tabstop=4
let g:ansicolorcodes_ignore_conceal = 1
set t_Co=16



" Return to last line
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

